In [1]:
import torch

print(f"PyTorch Version: {torch.__version__}")

PyTorch Version: 2.6.0+cu124


## pytorch 기초 텐서

### 1. Tensor

데이터를 처리하는데 Tensor라는 자료 구조를 사용

데이터를 표현하는 기본 도구 이며, 계산 및 딥러닝 모델의 가중치 계산에서 사용

<img src="https://res.cloudinary.com/practicaldev/image/fetch/s--8pw60d5S--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png">


텐서는 위와 같이 4개의 형태로 구분이 된다.
- 0차원 텐서 => 스칼라
- 1차원 텐서 => 벡터
- 2차원 텐서 => 행렬
- 3차원 텐서 => RGB 이미지 표현

In [16]:
import torch
# 스칼라
scalar = torch.tensor(5)
print(f'scalar : {scalar}')

# 벡터
vector = torch.tensor([1,2,3])
print(f'vector : {vector}')

# 행렬
matrix = torch.tensor([[1,2,3],[4,5,6]])
print(f'matrix : {matrix}')


# 3차원 배열 For RGB
array = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(f'array : {array}')
print(f'shape : {array.shape}')

scalar : 5
vector : tensor([1, 2, 3])
matrix : tensor([[1, 2, 3],
        [4, 5, 6]])
array : tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
shape : torch.Size([3, 2, 3])


Pytorch를 활용하면 다양한 텐서를 만들수 있다.

In [34]:
# 모든 요소를 0으로 채운 텐서
zeros_tensor = torch.zeros(2,3)
print(zeros_tensor)

# 모든 요소를 1로 채운 텐서
ones_tensor = torch.ones(2,2)
print(ones_tensor)

# 0부터 1까지 무작윈 난수가 생성 된 텐서
rand_tensor = torch.rand(2,2)
print(rand_tensor)

# 정규 분포(평균 0 , 표준편차 1)에서 난수가 생성 된 텐서
randn_tensor = torch.randn(2,2)
print(randn_tensor)

# 시작과 끝 사이게 균등하게 차이가 나게 n개가 생겅 된 1차원 텐서
linspace_tensor = torch.linspace(1, 10 , 5) # 시작과 끝을 포함
print(linspace_tensor)

# 시작과 끝 사이에 n씩 증가하는 1차원 텐서
arange_tensor = torch.arange(1,10,2) # 끝인 10은 포함 안해
print(arange_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.6335, 0.4750],
        [0.4620, 0.7347]])
tensor([[ 0.5696,  0.4204],
        [ 1.0093, -0.7085]])
tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([1, 3, 5, 7, 9])


### 2. tensor 속성
tensor속성 즉 데이터의 속성을 확인하기 위한 방법이 있다.

다시 말해
- 데이터의 형태
- 자료형태
- 연산 장치
- 차원 수
- 원소 개수 등

을 파악하기 위한 다양한 코드가 존재한다.


In [7]:
# 벡터 생성
vector = torch.tensor([1,2,3])
vector_float = torch.tensor([1.2, 2, 3])

# 데이터의 형태
print(f'데이터의 형태 : {vector.shape}')
## torch.Size([3]) 1차원 벡터 형태에 3개의 데이터 값(column)이 들어가 있다.

# 자료형태
print(f'자료형태 : {vector.dtype}')
## torch.int64

print(f'자료형태 : {vector_float.dtype}')
## torch.float32 하나라도 float이 있으면 float 형태로

# 연산 장치
print(f'연산 장치 : {vector.device}')
## cpu


데이터의 형태 : torch.Size([3])
자료형태 : torch.int64
자료형태 : torch.float32
연산 장치 : cpu


In [14]:
# 2차원 행렬 생성
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
## 주의 각 행에 대한 column의 갯수가 동일해야 한다.
### 즉 torch.tensor([[1, 2, 3], [4, 5]]) => ValueError 가발생한다.

# 데이터의 형태
print(f'데이터의 형태 : {matrix.shape}')
## torch.Size([2, 3]) 2행, 3열

# 차원의 수
print(f'차원의 수 : {matrix.ndim}')
## 2  2차원 행렬이다. 라고 알려주는 것

# 총 원소 개수
print(f'총 원소 개수 : {matrix.numel()}')
## 6 총 데이터의 갯수

데이터의 형태 : torch.Size([2, 3])
차원의 수 : 2
총 원소 개수 : 6


### 텐서의 차원 변환

ML, DL을 하는 과정에서 다양한 데이터를 마주하게 될 것이다.

차원 변환은 다양한 데이터를 모델의 입출력 형태에 맞추거나,
특정 공식을 수행하기 위해 진행하는 경우가 많다.

reshape()

In [20]:
reshape = torch.tensor([[1,2,3], [4,5,6]])
print(f"차원 변환 전 : {reshape.shape}")
# [2,3] 2행 3열

reshape = reshape.reshape(3,2)
print(f"차원 변환 후 : {reshape.shape}")
# [3,2] 3행 2열

# 1차원 벡터로의 변환
reshape = reshape.reshape(-1)
print(f"차원 변환 후 : {reshape.shape}")
# [6] 1차원 벡터
print(reshape) # tensor([1, 2, 3, 4, 5, 6])


차원 변환 전 : torch.Size([2, 3])
차원 변환 후 : torch.Size([3, 2])
차원 변환 후 : torch.Size([6])
tensor([1, 2, 3, 4, 5, 6])


### tensor의 자료형

In [24]:
tensor = torch.rand(2,3) # 2행 3열의 무작위 난수 생성
print(f"dtype :{tensor.dtype}") # dtype :torch.float32

tensor64 = torch.rand((2,3), dtype = torch.float64)
print(f"dtype :{tensor64.dtype}") # dtype :torch.float64

tensor_to = tensor.to(torch.float64)
print(f"dtype :{tensor_to.dtype}") # dtype :torch.float64

dtype :torch.float32
dtype :torch.float64
dtype :torch.float64


### 장치 설정

In [26]:
# CUDA 또는 CPU 장치 설정
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# CPU와 GPU에 각각 텐서 생성
cpu_tensor = torch.FloatTensor([1, 2, 3])
gpu_tensor = torch.cuda.FloatTensor([1, 2, 3]) if torch.cuda.is_available() else cpu_tensor

# 설정한 장치에 텐서 생성
tensor = torch.tensor([1, 2, 3], device=device)

# 출력
print(f"Device in use: {device}")
print(f"CPU Tensor: {cpu_tensor}")
print(f"GPU Tensor: {gpu_tensor}")
print(f"Tensor on {device}: {tensor}")

Device in use: cpu
CPU Tensor: tensor([1., 2., 3.])
GPU Tensor: tensor([1., 2., 3.])
Tensor on cpu: tensor([1, 2, 3])


### Pytorch 산술 연산

- 요소별 연산

  - PyTorch에서는 덧셈(+), 뺄셈(-), 곱셈(*), 나눗셈(/) 수행할 수 있다.

- 절댓값, 제곱근, 지수, 로그 연산

  - PyTorch는 절댓값(torch.abs()), 제곱근(torch.sqrt()), 지수(torch.exp()), 로그(torch.log()) 등 다양한 수학적 연산을 제공

In [35]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(f"a + b = {a + b}")  # 덧셈
print(f"a - b = {a - b}")  # 뺄셈
print(f"a * b = {a * b}")  # 요소별 곱셈
print(f"a / b = {a / b}")  # 요소별 나눗셈

a + b = tensor([5, 7, 9])
a - b = tensor([-3, -3, -3])
a * b = tensor([ 4, 10, 18])
a / b = tensor([0.2500, 0.4000, 0.5000])


### [벡터의 내적 (Dot Product) 정리]

1. 벡터 내적이란?

벡터의 내적 : 두 벡터가 얼마나 같은 방향을 향하고 있는지를 하나의 숫자로 나타내는 연산. 연산 결과는 방향이 없는 스칼라 값.

이 값은 두 벡터의 유사도를 측정하거나, 한 벡터가 다른 벡터에 얼마나 투영되는지를 계산하는 등 머신러닝과 선형대수학에서 사용

---

2. 계산 방법

내적은 각 벡터의 같은 위치에 있는 성분(component)끼리 곱한 후, 그 값들을 모두 더한다.

- 예시

  - 2차원 벡터 **a**와 **b**가 있을 때,

  - **a** = `[2, 3]`
  - **b** = `[4, 1]`

- 두 벡터의 내적 **a · b**는 다음과 같이 계산된다.

  - `(2 * 4) + (3 * 1) = 8 + 3 = 11`

따라서 두 벡터의 내적 값은 **11**

---

3. 내적의 기하학적 의미

내적의 결과값(부호)을 통해 두 벡터의 방향 관계를 직관적으로 파악 가능

* **내적이 양수(+)**: 두 벡터가 **비슷한(예각) 방향** (0° ≤ θ < 90°)
* **내적이 0**: 두 벡터가 서로 **수직(직각)** (θ = 90°)
* **내적이 음수(-)**: 두 벡터가 **반대(둔각) 방향** (90° < θ ≤ 180°)


In [37]:
# Python (Numpy) 코드로 내적 계산하기
import numpy as np

a = np.array([2, 3])
b = np.array([4, 1])

# np.dot() 함수 사용
dot_product = np.dot(a, b)

print(f"벡터 a: {a}")
print(f"벡터 b: {b}")
print(f"a와 b의 내적: {dot_product}")

# Pytorch로 내적 계산
m1 = torch.tensor([1,2,3])
m2 = torch.tensor([4,5,6])

dot = torch.dot(m1,m2)

print(f"m1 : {m1}")
print(f"m2 : {m2}")

print(f"m1과 m2의 내적 : {dot}")


벡터 a: [2 3]
벡터 b: [4 1]
a와 b의 내적: 11
m1 : tensor([1, 2, 3])
m2 : tensor([4, 5, 6])
m1과 m2의 내적 : 32


### 행렬 곱셈
- **@** 연산자
- **torch.matmul()**    OR    **행렬에 한해서면 torch.mm**

In [38]:
m1 = torch.tensor([[1, 2], [3, 4]])
m2 = torch.tensor([[5, 6], [7, 8]])

# @ 연산자
print(f"@ 연산자 행렬 곱:\n{m1 @ m2}")

# torch.mm()
print(f"torch.mm() 행렬 곱:\n{torch.mm(m1, m2)}")

# torch.matmul()
print(f"torch.matmul() 행렬 곱 : \n{torch.matmul(m1, m2)}")


@ 연산자 행렬 곱:
tensor([[19, 22],
        [43, 50]])
torch.mm() 행렬 곱:
tensor([[19, 22],
        [43, 50]])
torch.matmul() 행렬 곱 : 
tensor([[19, 22],
        [43, 50]])


### 통계 함수

PyTorch는 합계, 평균, 표준편차, 최대값 및 최소값 등의 통계 함수를 지원한다.

이를 통해 데이터를 분석하거나 모델 학습 중 중요한 통계 정보를 쉽게 계산할 수 있다.

- 합계: torch.sum()
- 평균: torch.mean()
- 표준편차: torch.std()
- 최대값, 최소값: torch.max(), torch.min()

최대값, 최소값의 인덱스를 반환하여 데이터의 위치를 파악하는데 유용하다.
- 최대값 index : torch.argmax()
- 최소값 index : torch.argmin()


In [40]:
st = torch.randn(3, 3)  # 3x3 랜덤 행렬 생성

print(st)
print("Sum", torch.sum(st))  # 모든 요소의 합
print(f"Mean: {torch.mean(st)}")  # 평균
print(f"Standard deviation: {torch.std(st)}")  # 표준편차
print(f"Max: {torch.max(st)}")  # 최대값
print(f"Min: {torch.min(st)}")  # 최소값

d = torch.tensor([10, 30, 15, 25])

print("Index max :", torch.argmax(d))  # 최대값의 인덱스
print("Index min :", torch.argmin(d))  # 최소값의 인덱스

tensor([[-0.2784, -0.0118,  1.0172],
        [ 0.6903, -0.0086,  1.4010],
        [ 0.0198,  1.5891,  2.3169]])
Sum tensor(6.7356)
Mean: 0.7483996152877808
Standard deviation: 0.8947514295578003
Max: 2.3168933391571045
Min: -0.27838099002838135
Index max : tensor(1)
Index min : tensor(0)
